### ISSUE TITLE
Missing favicon.ico

### ISSUE THREAD

**Issue by JoshuaHenriques** [nonunicorn/onelinerhub#126]
Filename: /favicon.ico
Status: 404 Not Found

**Comment by JoshuaHenriques** [comment]
close if intentional

**Comment by pranjay-poddar** [comment]
Please assign this task to me i would like to resolve this issue.

**Comment by nonunicorn** [comment]
Thank you guys! We're right in the middle of logo creation process now, will deploy favicon soon based on a new logo. Will update this ticket.

**Comment by nonunicorn** [comment]
Ok, we have it now :)
