### ISSUE TITLE
Short solution needed: "Rust lang loops" (rust)

### ISSUE THREAD

**Issue by nonunicorn** [nonunicorn/onelinerhub#1937]
Please help us write most modern and shortest code solution for this issue:
**Rust lang loops** (technology: [rust](https://onelinerhub.com/rust))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create [pull request](https://github.com/Onelinerhub/onelinerhub/blob/main/how-to-contribute.md) with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to [use comments](https://github.com/Onelinerhub/onelinerhub/blob/main/how-to-contribute.md#code-file-md-format) explain solution.
3. Link to this issue in comments of pull request.

**Comment by devmalik7** [comment]
**Infinite loops**

    *Syntax*
    InfiniteLoopExpression :
       loop [BlockExpression]

A loop expression repeats execution of its body continuously

**Predicate loops**

*Syntex*
while [Expression]
[BlockExpression]

A while loop begins by evaluating the boolean loop conditional operand.
