### ISSUE TITLE
Oneliner Hub Search in VSсode

### ISSUE THREAD

**Issue by pashkatrick** [nonunicorn/onelinerhub#258]
Thanks for Search API a lot!
Build simple extension https://marketplace.visualstudio.com/items?itemName=pashkatrick.oneliner
Hope, it'll useful not only for me :)

should me sign a copyrights? suggest me pls

**Comment by pashkatrick** [comment]
Got it! next version try to do it :)

**Comment by nonunicorn** [comment]
Also published a link under "Integrations" section:
https://github.com/Onelinerhub/onelinerhub/blob/main/README.md#integrations
