### ISSUE TITLE
Add Git code pieces

### ISSUE THREAD

**Issue by nonunicorn** [nonunicorn/onelinerhub#39]
Add Git code pieces you use frequently here:
https://github.com/nonunicorn/onelinerhub/tree/main/git

How to do it:
https://github.com/nonunicorn/onelinerhub/blob/main/README.md

**Comment by MeerHamza1421** [comment]
hey 👋, Can I contribute some git oneliners?

**Comment by nonunicorn** [comment]
> hey 👋, Can I contribute some oneliners?

Sure, just create a pull request. It's pretty simple using this [documentation](https://github.com/nonunicorn/onelinerhub/blob/main/README.md) or feel free to ask any questions here (or create issues if you find bugs / have new ideas)

Thanks!
