### ISSUE TITLE
Suggested copy area

### ISSUE THREAD

**Issue by nonunicorn** [nonunicorn/onelinerhub#42]
In chart.js code pieces it's more convenient to copy just a part of configuration options by default, instead of whole code example. Think of creating new markup way to highlight default copying area in such cases.

**Comment by axmad386** [comment]
Hi, this repo is just for snippet data of onelinerhub.com right? Are the main code of onelinerhub.com is private? May be someone will contribute to make any cool new feature if the main repo is public. Including me 🤣

**Comment by nonunicorn** [comment]
Sure, we're making it opensource in a month or so, cause now it's just a mess :)

**Comment by nonunicorn** [comment]
Created https://github.com/nonunicorn/onelinerhub/issues/79 to monitor this

**Comment by nonunicorn** [comment]
Returning to the initial issue, Indeed much better now: https://onelinerhub.com/chart.js/disable_animation
Documentation added here: https://github.com/nonunicorn/onelinerhub/blob/main/README.md
