### ISSUE TITLE
needs a "funny" section

### ISSUE THREAD

**Issue by gek169** [nonunicorn/onelinerhub#46]
hear me out alright

what if we could upload jokes to onelinerhub

dont lie this is a good idea

**Comment by nonunicorn** [comment]
ha ha :) any quick one-liner joke examples? :)

**Comment by gek169** [comment]
"Nice motherboard" - a real one liner

**Comment by nonunicorn** [comment]
Sorry :) I'm a bit stupid, haven't got it

**Comment by gek169** [comment]
a pickup line for nerds

**Comment by nonunicorn** [comment]
ah, ha ha :) let me discuss it internally

**Comment by nonunicorn** [comment]
Closing this as we couldn't agree on the format of the section. Might return to it on later stages, once we have covered at least most popular techs. Feel free to join us.
