### ISSUE TITLE
Add Postgres code (queries) pieces

### ISSUE THREAD

**Issue by nonunicorn** [nonunicorn/onelinerhub#95]
Add Postgres code pieces you use frequently here:
https://github.com/nonunicorn/onelinerhub/tree/main/postgres

How to do it:
https://github.com/nonunicorn/onelinerhub/blob/main/README.md

**Comment by Anvi98** [comment]
Hey, the first link above redirects to git commands and not Postgres !

**Comment by nonunicorn** [comment]
Sorry about that, bad focus, fixed :)

**Comment by JoshuaHenriques** [comment]
I can get started on this
